### ISSUE TITLE
Access to global attributes in generic REST/GraphQL query

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#111]
Consider following GraphQL query:

```graphql
query {
  getEntity(url: "/cs/doplnky") {
    primaryKey
    type
    ... on Category {
      locales
      attributes {
        name
        inactiveUrls
      }
    }
  }
}
```

To access global attributes, a developer must declare a full switch statement, which is cumbersome. The global attributes are guaranteed to have the same configuration in all entity schemas. The entity schema has only one option - it can choose to use the global attribute (with all its shared configuration) or not. It cannot redefine the attribute with a different data type or behavior.

Therefore, we can afford to provide access to global attributes directly in the generic query in the following way:

```graphql
query {
  getEntity(url: "/cs/doplnky") {
    primaryKey
    type  
    locales
    attributes {
      name
      inactiveUrls
    }  
  }
}
```

If the entity that doesn't use this global attribute is returned, it simply provides a NULL value for such an attribute. The query format will be much cleaner and easier for developers to understand. The gRPC and Java implementations are not affected by this extension because they already provide easy access to global attributes.

The next problem is with the query's implicit `AND' relation. There are cases where we would want to use `OR` instead - real world use case ... finding an unknown entity by its active URL or one of its inactive URLS:

```graphql
getEntity(url: "/en/accessories", urlInactive: "/en/accessories", joinType: OR)
```

We don't want to open up this generic method to full `filterBy' capabilities since it is rather limited and can effectively only search for globally unique attributes and nothing else. However, the wrapper container is a feature that would allow us to get rid of unnecessary additional requests.

**Comment by lukashornych** [comment]
After further discussion, there are multiple problems with the originally proposed functionality, primarily because of how the GraphQL works:

1) Because an entity schema is not obligated to use a global attribute of a catalog schema, a specific attribute in the entity interface may be null even though it may be set as non-nullable in evitaDB schema, otherwise GraphQL would return error if that attribute in any entity would be missing. We would have to set such attributes to nullable in GraphQL schema and ignore nullable flag in evitaDB attribute schema, which is no very good idea, because we would lost part of the self-documenting feature of GQL API.

2) Another problem is with localized attributes, primarily with how to set locale for the localized attributes in the `attributes` field. Global attributes can be localized as well, but `CatalogSchema` doesn't have any `getLocales` to build enum of global locales from. Even if it did, and we used it in the `attributes` field in entity interface, implementations of the interface for concrete collection
would need different enums with locales specific to its collection.

The only viable solution that we can think of and that make sense right now, would be to completely split the unknown entity queries and specific-collection queries, where unknown entity queries would not have entity interface but rather entity type that would contain only shared fields for all entities (pk, type, attributes), and collection-specific entity types would implement no interface.

**Comment by lukashornych** [comment]
We agreed on proposed solution:
>The only viable solution that we can think of and that make sense right now, would be to completely split the unknown entity queries and specific-collection queries, where unknown entity queries would not have entity interface but rather entity type that would contain only shared fields for all entities (pk, type, attributes), and collection-specific entity types would implement no interface.

Still, we need to think about locales. In our case, the `url` is localized and the locale is determined implicitly, what about cases where we use non-localized attribute in filter and wanted different localized attribute?

**Comment by novoj** [comment]
> Still, we need to think about locales. In our case, the `url` is localized and the locale is determined implicitly, what about cases where we use non-localized attribute in filter and wanted different localized attribute?

I guess we need to add support for (optionally) declaring a single language code taken from the all languages supported by target catalog and add it to the `filterBy` part of the query. When language will not be specified and global attribute is used for lookup, no localized attributes will be returned.

**Comment by lukashornych** [comment]
The final proposed solution has been implemented with possibility to specify `locale` argument for attributes.
