### ISSUE TITLE
Investigate bottlenecks in graphql-java library

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#201]
The GraphQL implementation is noticeably slower than REST, but it's the key API for the Edee.ONE implementation, so it's worth investing a day or two to investigate possible performance optimizations inside the graphql-java library.

One problem is documented here: https://github.com/graphql-java/graphql-java/issues/3256#issuecomment-1648978966

But there is a suspicion that another bottleneck is at the point where the output objects are rendered - the more complex objects are serialized, the slower the response is (according to our performance test measurements).

**Comment by lukashornych** [comment]
I've managed to fix a lots of small perf. issues in our code base that helped a lot, These changes also affected REST API as the changes were as most of them were done in core API. The mentioned bottleneck with GQL field resolution were done on our side in `SelectionSetAggregator` which is wrapper around GQL Java library toolset. This is because I was able to create more stripped down version of field lookup because we don't need almost any pattern matching which the GQL Java lib supports by default and would be probably required if we submitted a PR, which is still an unnecessary overhead for our use-case.

**Comment by novoj** [comment]
Will you submit them at least PR with exchanged for loop you've shown me?

**Comment by lukashornych** [comment]
I can do that, although I don't know if it will has any real world impact on majority use-cases (how majority of people use that lib). But some activity from could be good, I think.

**Comment by novoj** [comment]
GraphQL Java is used a lot. If it is a small PR, it has a very good chance of being accepted without much discussion. Let's see - we owe them a protocol, so why not give something back?

**Comment by lukashornych** [comment]
Yeah, I though the same. I will prepare it.
