### ISSUE TITLE
Incorrect BigDecimal conversions in gRPC

### ISSUE THREAD

**Issue by Khertys** [FgForrest/evitaDB#285]
While testing the C# client, I ran into a problem with `decimal` number conversions. Currently, the gRPC representation of Java's BigDecimal is sufficient and functional in Java, but the `scale` and `precision` values used caused conversion problems, resulting in bad numbers being converted. I have found an official and supposedly [most compatible way](https://github.com/googleapis/googleapis/blob/master/google/type/decimal.proto) of representing such values, specifically as a `String`, which is recommended by Google.

**Comment by lukashornych** [comment]
Regarding the [described decimal normalization](https://github.com/googleapis/googleapis/blob/master/google/type/decimal.proto): turns out the Java's BigDecimal already handles majority of the examples. Remaining edge cases were  handled in `EvitaDataTypes.formatValue` we send decimal values out of evitaDB normalized from every API (gRPC, GQL, REST) as they all use string to represent decimal values.
