### ISSUE TITLE
Implement parallelism for GraphQL resolvers

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#36]
As we find out during status meeting, currently the queries in GraphQL implementation are evaluated serially. If the GraphQL request contains 3 queries A,B,C they will be evaluated in that order one after another. The proper implementaiton is that each query is executed within single task passed to the evitaDB thread pool and than the main process should wait for each of it to be processed using [latch](https://www.baeldung.com/java-countdown-latch).

**Comment by lukashornych** [comment]
I've implemented it using CompletableFutures as mentioned in [GraphQL library blog](https://www.graphql-java.com/blog/threads). Async data fetcher are only those which requests some data directly from evitaDB or its session. Other data fetchers that fetch data from previously fetcher parent object are not async as this would create memory overhead (by creating a lot of CompletableFutures for non-IO fetches) a could cause bottleneck when trying to pass every operation to worker thread without reason.

There is a simple test for it `io.evitadb.externalApi.graphql.api.catalog.dataApi.CatalogGraphQLAsyncQueriesFunctionalTest#shouldCorrectlyHandleMultipleParallelQueries`. It is disabled by default because when run in parallel with other tests, processor probably didn't have enough threads available for all subqueries in that one test to run them in parallel and the test failed.
