### ISSUE TITLE
Predecessor ordering used in facet statistics doesn't work

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#393]
When attribute of `Predecessor` type is used to sort facet statistics, evitaDB doesn't sort the facet statistics within groups. 
```
query(
	collection('Product'),
	filterBy(
		entityLocaleEquals('cs')
	),
	require(
		page(1, 20),
		facetSummaryOfReference(
			'groups',
			COUNTS,
			orderBy(
				attributeNatural('order', ASC)
			),
			entityFetch(
				attributeContent('name', "order"),
				dataInLocales('cs')
			)
		)
	)
)
```
Other string attributes work as expected.

**Comment by novoj** [comment]
I've added `io.evitadb.api.EntityByFacetFilteringFunctionalTest#shouldReturnSortedFacetStatisticsByPredecessorAttribute` test to branch `393` and corrected one issue that related to the attribute schema being looked up in wrong entity schema. But this bug caused AttributeSchemaNotFound in my case and not skipping the ordering as you suggest in the heading of this issue. Can you look at the test and verify, that it's on par with the problem reported by users?

**Comment by novoj** [comment]
I've manually checked that the reported problem related to the fix I found using the test. The problem was as follows:

- `Product` has attribute `order` as `Long` type
- `Group` has attribute `order` as `Predecessor` type

When ordering in facets was evaluated the used entity schema was the schema for Product and different attribute schema was found and used for ordering. This also explains why the ordering in grid worked - because in grid the main schema of the queried entity is `Group`.
