### ISSUE TITLE
Access to all prices for sale in case of price inner record handling FIRST_OCCURENCE / SUM

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#486]
There are scenarios where the frontend needs to access all calculated prices for the sale. For example, to differentiate whether products with a `FIRST_VARIANT` price selection strategy display the prefix `from`. It's certainly a good idea to distinguish the situation where all prices are the same and the prefix `from` is unnecessary, and the case where the product variants have different sales prices and the sales price used represents only the lowest price of them all.

In graphQL it seems a good idea to add variant to add new optional section:

```graphQL
pricesForSale(validNow: true, currency: $currency) {
    ...fieldsPrice
}
```

This would return all sale prices for certain inner record ids. We can also provide a simple property on the `priceForSale' object called `multiplePricesForSale' which would return `true`/`false` to signal if there are multiple prices for sale behind the selected one.

On the Java level this data are already available via method `io.evitadb.api.requestResponse.data.PricesContract#getAllPricesForSale(java.util.Currency, java.time.OffsetDateTime, java.lang.String...)` - we just need to propagate them to REST / GraphQL API.

**Comment by lukashornych** [comment]
@novoj I don't think we can do it similarly easy in REST as in GQL without introducing separate endpoint for prices. Because in REST we use standard priceContent constraints for fetching prices, the priceContent doesn't have such option.
I could either return all prices for sale automatically when `PriceContentMode.ALL` is requested, or we could introduce another `PriceContentMode` similar to `RESPECTING_FILTER` which would return the price for sale as well as the rest of prices for sale.

**Comment by novoj** [comment]
I don't understand. If you use `RESPECTING_FILTER` in price content - you'll receive ALL PRICES FOR SALE in the returned entity. But as I study the implementation you'd get really all the prices that are participating in the calculation - we lack method that would return winning prices for sale for each inner record id. I'd have to add such method.

**Comment by lukashornych** [comment]
So, we have new fields in GQL `allPricesForSale` and `multiplePricesForSaleAvailable` where the first one can take arguments to calculate custom prices besides the main query the same way `priceForSale` field does. 
In REST, there is new `multiplePricesForSaleAvailable` property for entities that have price inner record handling `FIRST_OCCURENCE` or `SUM`.

**Comment by lukashornych** [comment]
Reopening this issue because we need to rework the `multiplePricesForSaleAvailable` behaviour.

After some discussion we agreed on following behaviour:

- NONE:
  -  always `false` - there isn't a scenario where `NONE` returns multiple prices for sale
- FIRST_OCCURENCE:
  - price for sale for only one `innerRecordId` -> `false`
  - prices for sale for multiple `innerRecordId`s that have different price values -> `true`
  - prices for sale for multiple `innerRecordId`s that all have the same price value -> `false`
- SUM:
  - price for sale for only one `innerRecordId` -> `false`
  - prices for sale for multiple `innerRecordId`s no matter the price values -> `true`

We need to somehow be able to tell if two prices for sale for different `innerRecordId`s have same value, but we have `priceWithoutVat`, `priceWithVat` and the `vat`. We've agreed to use the `priceType` for determining by which value to compare so that it is up to the client to specify it's use-case. So if `priceType = WITH_VAT` we will use the `priceWithVat` of each price to compare sameness, if `priceType = WITHOUT_VAT` we will use the `priceWithoutVat` of each price to compare sameness.

The same logic for comparing we will use for sorting the `allPricesForSale` array returned from GraphQL API (this is new as well), so that FEs can easily determine lowest and highest values.

**Comment by novoj** [comment]
I've updated the computation - please push your changes as a fix so that we don't trigger next major version - only patch. Thanks.
