### ISSUE TITLE
GraphQL/REST APIs allow EntityProperty constraint but evitaDB doesn't

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#492]
We've found out that GraphQL and REST APIs allow `entityProperty` order constraint inside a `referenceProperty` constraint like [so](https://demo.evitadb.io/lab?sharedTab=N4IgLghgRgKgngBwKYgFwgOYCcIIBYCKAMgMID2AdgM5kA2KANONAAoQ4C2VaoAxpRSS8wAS0oBJACZoQkpBzIgmvCJFpkMAOQgcU6JADcRkJSBHVIFXknjIZk1RBABfJpCgARRzxABHAK5IWHAywAA6FAAEkbQiVGAsWGSS-sIAFBHR0WRYclgAQnCo4VFZ0VhIAGZBSFZIbJxIYEEAahC0gVSJZMhYYEWRJWVltaL93b39qIOZw2UV1RV1DTpNQRNBUzOlc2WqYFgiUP7NAPK5QeIUK7rNWNpg-ji00wCCAMoks7uRzt-Dfx2WUBZRBkQAlNsyghDhx2HAANJIOCzZzRCLOUwGdgiaD0bjoIaRDEuZxAA).  But this throw an error because core of evitaDB doesn't support such deep ordering. 

So far, I think the mistake is in the GQL/REST constraint schema builder because we don't have indexes for such deep ordering, but it needs to be discussed.

**Comment by novoj** [comment]
Yes, currently the ordering can only be done on the data of the queried entity. We could go deeper, but still the references have to have the cardinality ONE_TO_ZERO_OR_ONE or ONE_TO_EXACTLY_ONE, otherwise the ordering would make no sense. So the GraphQL schema would have to limit the ordering of the entity properties to references of that cardinality.

I propose to limit the GraphQL query language to the current capabilities of the core engine in this issue, and open a new issue where we extend the ordering to nested entities of the mentioned cardinality.

**Comment by lukashornych** [comment]
Yes, I agree, I came to the same conclusion with the cardinalities.
