### ISSUE TITLE
Entity archiving (soft-delete support)

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#677]
Some e-commerce implementations provide access to products long after they are no longer offered and manufactured. These products are usually used as a source of technical information or simply for SEO purposes and linking to orders or customer history. It doesn't make sense to keep these products in active indexes in RAM, and it's usually not wanted. These products are likely to be searched only by their primary key or URL and nothing else. Some clients solve this problem by introducing a separate entity collection - something like `ObsoleteProduct`, but this solution complicates the result schema because all relations to the old products (like related products or category products) need to be duplicated and rewired to a new entity type.

To simplify this common scenario, let's introduce entity archiving. This state will behave like ["soft delete"](https://en.wiktionary.org/wiki/soft_deletion) - i.e. the data will remain in place, but will be flagged as archived and excluded from search indexes (and there from occupying RAM). They'll only remain in indexes explicitly marked as valid, even for archived entities.

A new `archivedEntities` requirement will also be added, which will cause the client issuing the query to expect archived entities to be returned along with the active ones. Of course, the query must filter the entities by indexes/primary keys that are also available for archived entities in order to find them.

- [x] add tests for changing entity scope in GraphQL / REST API
- [x] support for `scope` requirement in GraphQL / REST API queries (one / list / paginated) + tests
- [x] add documentation / examples for scope requirement

**Comment by lukashornych** [comment]
Added `breaking change` tag, because there will be breaking changes in GQL and REST API input mutation objects as well as response schema API objects due to the scopes API.

**Comment by lukashornych** [comment]
**Another breaking change in GraphQL and REST API concerns generated `WrapperObjectXXX` input objects**. The breaking change should concern only object names, not the structure of objects itself. Changed should be only wrapper objects containing child constraint parameters.

This is due to an incorrect reusability mechanism of wrapper objects. The issue was that during checking if a wrapper object can be reused in another place, the mechanism didn't take current context (constraint domains, globally allowed/forbidden constraints, ...) into consideration, resulting in incorrect wrapper objects when containing child constraint parameters (potentially missing available constraints and vice versa).
